/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.Sphere;
import java.awt.Color;
import java.awt.Graphics;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Gabriel
 */
public class CanvasPanel extends javax.swing.JPanel implements Runnable{
    
    private Thread thread;
    
    /**
     * Creates new form CanvasPanel
     */
    public CanvasPanel() {
        initComponents();
        thread = new Thread(this);
    }
    
    public void paintBackground(Graphics g) {
        g.clearRect(0, 0, getWidth(), getHeight());
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        paintBackground(getGraphics());
    }

    @Override
    public void run() {
        try {
            while(true) {
                paintBackground(getGraphics());
                Thread.sleep(70);
            }
        } catch (Exception e) {
        }
    }

    public void start() {
        if (!thread.isAlive()) {
            thread.start();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
